# generated by AI
import logging
from logging.handlers import RotatingFileHandler

LOG_FILE_PATH = "gh2.log"


def setup_logging(debug: bool = False):
    """
    配置全局日志记录。
    应在应用程序启动时尽早调用。
    """
    # 1. 定义日志格式
    log_format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

    # 2. 确保日志目录存在

    # 3. 配置根logger
    root_logger = logging.getLogger()
    if debug:
        root_logger.setLevel(logging.DEBUG)  # 设置全局最低日志级别
    else:
        root_logger.setLevel(logging.INFO)  # 设置全局最低日志级别

    # 4. 清除已有的handler（防止重复配置）
    if root_logger.handlers:
        root_logger.handlers.clear()

    # 5. 添加文件handler（带轮转功能，避免日志文件过大）
    file_handler = RotatingFileHandler(
        LOG_FILE_PATH,
        maxBytes=10 * 1024 * 1024,  # 10MB
        backupCount=5,  # 最多保留5个备份
        encoding="utf-8",
    )
    file_handler.setFormatter(logging.Formatter(log_format))
    root_logger.addHandler(file_handler)

    # 6. 添加控制台handler
    # console_handler = logging.StreamHandler()
    # console_handler.setFormatter(logging.Formatter(log_format))
    # root_logger.addHandler(console_handler)

    # 记录一条日志，确认配置已完成
    logging.info("全局日志配置已初始化。")


# 你也可以在这里定义一些日志过滤器或自定义Handler
